# Generated by Django 4.2.7 on 2023-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHEMS_v1', '0003_customer_user_delete_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
